-- Create Debezium CDC User (C##DBZUSER) and Sink Writer User (SYNC_WRITER) on Branch Server
-- Run as SYSDBA

-- Connect to PDB
ALTER SESSION SET CONTAINER=ORCLPDB;

-- Create C##DBZUSER for Debezium CDC
CREATE USER C##DBZUSER IDENTIFIED BY "OraclePa$$w0rd" CONTAINER=ALL;

-- Grant necessary privileges to C##DBZUSER
GRANT CREATE SESSION TO C##DBZUSER CONTAINER=ALL;
GRANT CONNECT TO C##DBZUSER CONTAINER=ALL;
GRANT RESOURCE TO C##DBZUSER CONTAINER=ALL;

-- Grant SELECT on all tables in Z12026 and ZLAB schemas to C##DBZUSER
-- This grants select on all tables, adjust if specific schemas are needed
GRANT SELECT ANY TABLE TO C##DBZUSER CONTAINER=ALL;

-- Grant LogMiner privileges to C##DBZUSER
GRANT EXECUTE ON DBMS_LOGMNR TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ROLLNAME TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$INSTANCE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##DBZUSER CONTAINER=ALL;

-- Grant privileges on DBA views to C##DBZUSER
GRANT SELECT ON DBA_OBJECTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_TABLES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_TAB_COLUMNS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_CONSTRAINTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_CONS_COLUMNS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_INDEXES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_IND_COLUMNS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_SEQUENCES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_SYNONYMS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_VIEWS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_TAB_PRIVS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_ROLE_PRIVS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_USERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_SEGMENTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_EXTENTS TO C##DBZUSER CONTAINER=ALL;

-- Grant privileges for supplemental logging to C##DBZUSER
GRANT ALTER SYSTEM TO C##DBZUSER CONTAINER=ALL;
GRANT ALTER DATABASE TO C##DBZUSER CONTAINER=ALL;

-- Create SYNC_WRITER user for sink operations
CREATE USER SYNC_WRITER IDENTIFIED BY "OraclePa$$w0rd"
    DEFAULT TABLESPACE LOGMINER_TBS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL;

-- Grant necessary privileges to SYNC_WRITER
GRANT CREATE SESSION TO SYNC_WRITER CONTAINER=ALL;
GRANT CONNECT TO SYNC_WRITER CONTAINER=ALL;
GRANT RESOURCE TO SYNC_WRITER CONTAINER=ALL;

-- Grant INSERT, UPDATE, DELETE on Z12026 and ZLAB schemas to SYNC_WRITER
-- This grants DML on all tables, adjust if specific schemas are needed
GRANT INSERT ANY TABLE TO SYNC_WRITER CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO SYNC_WRITER CONTAINER=ALL;
GRANT DELETE ANY TABLE TO SYNC_WRITER CONTAINER=ALL;

-- Verify user creation
SELECT username, account_status FROM dba_users WHERE username IN (
    UPPER("C##DBZUSER"), UPPER("SYNC_WRITER")
);
